name: gdod 2

on:
  schedule:
    - cron: 0 1/6 * * *
  workflow_dispatch:
    inputs:
    
jobs:
  copy:
    runs-on: ubuntu-latest
    name: GD to OD

    steps:
      - uses: actions/checkout@v2
      - name: gclone Install
        run: |
          wget -qO- https://api.github.com/repos/donwa/gclone/releases/latest \
          | grep browser_download_url | grep Linux_x86_64 | cut -d '"' -f 4 \
          | wget --no-verbose -i- -O- | gzip -d -c > gclone
          sudo mv gclone /usr/bin
          sudo chmod +x /usr/bin/gclone
      - name: gclone Config
        run: |
          curl -L "${{ secrets.SA_CONF_ZIP }}" -o sa-conf.zip
          unzip -q -P ${{ secrets.ZIP_PASS }} sa-conf.zip
          unzip -qq sa.zip
      - name: gclone Run
        run: |
          echo "::add-mask::gclone sa file: accounts/*"
          echo "::add-mask::.*.json"
          gclone copy --config ./conf-od2021.txt ${{ secrets.GDOD_2 }} --drive-server-side-across-configs --drive-acknowledge-abuse \
          --transfers=16 --checkers=32 --stats=5m0s --stats-one-line-date --stats-log-level NOTICE
